### ISSUE TITLE
Rebel Penguin

### ISSUE THREAD

**Issue by MikaelTorstensson** [moonwalker/marketing#10]
Rebel Penguins most profitable product today is pop-unders.

They seems to be one of the best in the industry doing pop-unders.
They are working closely with several networks to be able to handpick domains using an NDA.
They also have several security systems to make sure they don't end up on porn and torrent sites.
They more or less are the only partner with Bet365 when it comes to pop-unders due to their quality.

Cost: 15% of investment

Thinking we should do a test with them.

Would require 3-4 different landing pages to be able to optimise.
Remove all tracking on these sites except affiliate tracking (which should include affiliate, PPC, media buy, etc).

 - Could "steal" traffic with last click from affiliates
-  Could give bad branding effect. Very limited risk because of industry.
- Scale able channel 

Contract needs to be setup

**Comment by thetinman** [comment]
@MikaelTorstensson is this golive crucial? (not questioning, asking ;))
