### ISSUE TITLE
SMS Service

### ISSUE THREAD

**Issue by MikaelTorstensson** [moonwalker/marketing#11]
- [x] Check integration API

Cheap SMS Service. 
Says they have a good working API as well.
According to Linkedin they are working with Dunder, Nelly and NetOnNet.
I know for a fact that they have been working with NetOnNet and could easily check if they are working with Nelly.

Jojka Communication AB
Contact: Rutger Lindquist

**Comment by MikaelTorstensson** [comment]
[API-dokumentation_EN.pdf](https://github.com/moonwalker/marketing/files/1660147/API-dokumentation_EN.pdf)
API documentation

**Comment by LisaNowak** [comment]
[Wiraya Number verification.pdf](https://github.com/moonwalker/marketing/files/1663451/Wiraya.Number.verification.pdf)
[Wiraya_API.pdf](https://github.com/moonwalker/marketing/files/1663452/Wiraya_API.pdf)

**Comment by thetinman** [comment]
@wulkan @LisaNowak we need a short discussion about how we use this service in detail. Will you guys sync up?

**Comment by LisaNowak** [comment]
We must speak with Wiraya regarding direct unsubscription for players via SMS to request implementation, they should be well aware of what is required. Unsubscribe data needs to be sent to GiG as per the following document 
[2018.05.23 - Unsubscribe users through API.pdf](https://github.com/moonwalker/marketing/files/2047329/2018.05.23.-.Unsubscribe.users.through.API.pdf)

**Comment by LisaNowak** [comment]
@thetinman, @wulkan, availible at any time
