### ISSUE TITLE
Tracking Adform

### ISSUE THREAD

**Issue by MikaelTorstensson** [moonwalker/marketing#6]
To be able to optimise properly in Adform we need the following information from Google Tag Manager:
- NRC
- FTD
- Amount EUR
- Segment Low/Mid/High
- UserID
- If the User has an affiliate tag as NRC (lower return).
- Tracking points, 
               - Started NRC flow but didn't go through.
               - Started NDC flow but didn't go through

All tags in Google Tag Manager can be setup by me as long as the variables exists in Tag Manager.

**Comment by thetinman** [comment]
Dependent on #25

**Comment by thetinman** [comment]
https://github.com/moonwalker/lifesupport/issues/5
